### ISSUE TITLE
Should skip kube-system namespace early in MutatingWebhookConfiguration

### ISSUE THREAD

**Issue by jessehu** [k8tz/k8tz#76]
We came across an error case that when kube-proxy and k8tz pod are scheduled to the same K8s node, creating kube-proxy pod fails as the k8s apiserver is not able to connect to k8tz webhook server. It's because the k8tz webhook Service depends on kube-proxy to write the routing rule via iptables.

This error might happen since the lastest k8tz code skips injecting kube-system namespace in the webhook [handleFunc()](https://github.com/k8tz/k8tz/blob/master/pkg/admission/admission.go#L147-L148), but not in MutatingWebhookConfiguration via [namespaceSelector](https://github.com/k8tz/k8tz/blob/master/charts/k8tz/templates/admission-webhook.yaml#L27-L33).

cc @klzsysy

**Comment by yonatankahana** [comment]
Hi @jessehu,
you can make the webhook ignore the namespace with a simple annotation, i.e:

```bash
kubectl annotate namespace kube-system k8tz.io/controller-namespace=true
```

but, k8tz is designed to inject timezones to all pods on cluster, including kube-system. when used in production, it is recommended to spin up at least 3 replicas of k8tz to make sure the admission controller is highly available and prevent such chicken-and-egg cases.

i do thinking about adding another annotation that will allow users to make their namespaces ignored on the webhook level. `k8tz.io/controller-namespace` is not intuitive and made for internal usage. i'm thinking something like `k8tz.io/webhook-ignore=true`. i'm in a bit of a busy time, if you'd like to jump in and add the annotation in the helm chart and update the README accordingly - feel free and invited!

**Comment by jessehu** [comment]
Hi @yonatankahana , a bit confused on "k8tz is designed to inject timezones to all pods on cluster, including kube-system. when used in production", as this code explicitly ignores kube-system: https://github.com/k8tz/k8tz/blob/master/pkg/admission/admission.go#L147-L148

**Comment by tothdavid** [comment]
We just faced the same issue. Basically we deleted all node groups in an EKS cluster and after creating a new one nothing was able to start up (the nodes were stuck in a NotReady state because pods required to initialize the nodes were not able to start up because of the failed webhook) because of the missing admission controller service.  
So I really think you should consider adding the option to the helm chart @jessehu is proposing, and since you actually do ignore and pods starting up in the kube-system namespace it makes sense to ignore that namespace by default. In the meantime we will do the same workaround as proposed in the previous comment.

**Comment by tothdavid** [comment]
If you are interested I have created a PR based on the suggested solution.

**Comment by yonatankahana** [comment]
@jessehu 
> this code explicitly ignores kube-system

yes, you are right. i missed it.

@tothdavid 

thanks, ill take a look!
